# Generated by Django 2.0.13 on 2021-03-03 20:55

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_auto_20181115_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='included_categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='includes', to='catalogue.Category', verbose_name='Included Categories'),
        ),
    ]
